### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by kewell2000** [TeavenX/py2fa#1]
你好，根据说明，新建config.yaml并配置好后，双击app启动报错
![image](https://user-images.githubusercontent.com/28219501/214628423-1fd5664d-24ea-4591-82d1-b68df8e64ae0.png)

系统：macOS 13.1 ventura 
m1 max

**Comment by TeavenX** [comment]
在终端中执行以下命令，然后贴一下日志看看
```shell
/Applications/PY2FA.app/Contents/MacOS/PY2FA
```

**Comment by kewell2000** [comment]
Traceback (most recent call last):
  File "/Applications/PY2FA.app/Contents/Resources/__boot__.py", line 30, in <module>
    import ctypes
  File "<frozen zipimport>", line 259, in load_module
  File "ctypes/__init__.pyc", line 7, in <module>
ImportError: dlopen(/Applications/PY2FA.app/Contents/Resources/lib/python3.8/lib-dynload/_ctypes.so, 0x0002): Library not loaded: @rpath/libffi.7.dylib
  Referenced from: <A5004B20-D049-3375-BF6A-BEE21F956198> /Applications/PY2FA.app/Contents/Resources/lib/python3.8/lib-dynload/_ctypes.so
  Reason: tried: '/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/Applications/PY2FA.app/Contents/Resources/lib/python3.8/lib-dynload/../../libffi.7.dylib' (no such file), '/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/Applications/PY2FA.app/Contents/Resources/lib/python3.8/lib-dynload/../../libffi.7.dylib' (no such file), '/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/Applications/PY2FA.app/Contents/Frameworks/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/libffi.7.dylib' (no such file), '/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/Applications/PY2FA.app/Contents/Resources/lib/python3.8/lib-dynload/../../libffi.7.dylib' (no such file), '/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/Applications/PY2FA.app/Contents/Resources/lib/python3.8/lib-dynload/../../libffi.7.dylib' (no such file), '/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/teaven/opt/anaconda3/envs/py2fa/lib/libffi.7.dylib' (no such file), '/Applications/PY2FA.app/Contents/Frameworks/libffi.7.dylib' (no such file), '/usr/local/lib/libffi.7.dylib' (no such file), '/usr/lib/libffi.7.dylib' (no such file, not in dyld cache)
2023-01-29 09:31:50.967 PY2FA[21680:1026530] PY2FA Error
(base)

貌似是ctypes这个包的问题？我尝试pip安装没成功，ERROR: Could not find a version that satisfies the requirement ctypes (from versions: none)
ERROR: No matching distribution found for ctypes

**Comment by TeavenX** [comment]
应该是打包成app的问题，你用readme写的步骤在本地重新打包一下看看

**Comment by kewell2000** [comment]
一、执行python setup.py py2app这一步报错：
WARNING: ImportError in sip recipe ignored: No module named strsimpy-0
WARNING: ImportError in sip recipe ignored: No module named jupyter-1
WARNING: ImportError in sip recipe ignored: No module named pyobjc_framework_GameController-9
......
RecursionError: maximum recursion depth exceeded while calling a Python object
(base)
二、
另外，我把代码复制下来，在本地环境下实例化执行也报错了。
ERROR:root:'utf-8' codec can't decode byte 0x89 in position 1: invalid start byte
......
File "/Volumes/xxxxxx/test.py", line 164, in parse_content
    text_html = self.decode_bs64(content[1].as_string().split('base64')[-1])
IndexError: list index out of range
我在gmail上设置的pop收取规则是对从现在起收到的邮件启用POP。
另外 ，我用其他的pop3代码在本地测试收取gmail很卡，时断时收。
你正常运行的时候没有这个问题吗？

**Comment by kewell2000** [comment]
你好，我又试了好几次本地运行代码。
有时候可以获取到邮件信息，但是解码似乎有问题？
拿不到解码后的信息，有时候会报错：
ERROR:root:'utf-8' codec can't decode byte 0x89 in position 1: invalid start byte
